# action.yml
name: 'Keycloak Admin CLI'
description: 'Executes Keycloak Admin CLI against a defined server.'
branding:
  icon: 'unlock'
  color: 'blue'
inputs:
  version:
    description: 'The version of the keycloak image client to use'
    required: false
    default: "latest"
  server:
    description: 'The server URL e.g. http://localhost:8080/auth'
    required: true
  username:
    description: 'The username to start a session.'
    required: true
  password:
    description: 'The password to start a session.'
    required: true
  realm:
    description: 'The realm to start a session against to (default master).'
    required: false
    default: master
  client:
    description: 'The client to start a session against to (default admin-cli).'
    required: false
    default: admin-cli
  server-wait-timeout:
    description: 'Time to wait until server is available.'
    required: false
    default: "120"
  kcadm:
    description: 'The commands to execute after authenticated in Keycloak e.g. update realms/rhamt -f rhamt-realm.json.'
    required: true
runs:
  using: docker
  image: Dockerfile
  env:
    KEYCLOAK_VERSION: ${{ inputs.version }}
  args:
    - ${{ inputs.server }}
    - ${{ inputs.username }}
    - ${{ inputs.password }}
    - ${{ inputs.realm }}
    - ${{ inputs.client }}
    - ${{ inputs.server-wait-timeout }}
    - ${{ inputs.kcadm }}
