# action.yml
name: 'Keycloak Admin CLI'
description: 'Executes Keycloak Admin CLI against a defined server.'
branding:
  icon: 'unlock'
  color: 'blue'
inputs:
  version:
    description: 'The version of the keycloak image client to use'
    required: false
    default: "latest"
  server:
    description: 'The server URL e.g. http://localhost:8080/auth'
    required: true
  username:
    description: 'The username to start a session.'
    required: true
  password:
    description: 'The password to start a session.'
    required: true
  realm:
    description: 'The realm to start a session against to (default master).'
    required: false
    default: master
  client:
    description: 'The client to start a session against to (default admin-cli).'
    required: false
    default: admin-cli
  server-wait-timeout:
    description: 'Time to wait until server is available.'
    required: false
    default: "120"
  kcadm:
    description: 'The commands to execute after authenticated in Keycloak e.g. update realms/rhamt -f rhamt-realm.json.'
    required: true
runs:
  using: composite
  steps:
    - name: Download Keycloak client
      shell: bash
      env:
        KEYCLOAK_VERSION: ${{ inputs.version }}
      run: |
        KEYCLOAK_IMG=quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}

        mkdir -p /tmp/keycloak
        img=$(docker create --name download $KEYCLOAK_IMG ls)
        (docker cp $img:/opt/keycloak/bin /tmp/keycloak/bin || docker cp $img:/opt/jboss/keycloak/bin /tmp/keycloak/bin) && docker rm download
        
    - name: Execute client
      shell: bash
      env:
        SERVER_URL: ${{ inputs.server }}
        USERNAME: ${{ inputs.username }}
        PASSWORD: ${{ inputs.password }}
        REALM: ${{ inputs.realm }}
        CLIENT: ${{ inputs.client }}
        TIMEOUT: ${{ inputs.server-wait-timeout }}
        COMMAND: ${{ inputs.kcadm }}
      run: |
        attempt_counter=0
        interval=3
        max_attempts=$(($TIMEOUT/interval));

        ## Wait until server is ready to continue
        echo "Waiting for $SERVER_URL"
        until (curl --output /dev/null --silent --head --fail $SERVER_URL); do
          if [ ${attempt_counter} -eq ${max_attempts} ];then
            echo "Max attempts reached"
            exit 1
          fi

          printf '.'
          attempt_counter=$(($attempt_counter+1))
          sleep $interval
        done

        ## Login
        /tmp/keycloak/bin/kcadm.sh config credentials \
        --server ${SERVER_URL} \
        --user ${USERNAME} \
        --password ${PASSWORD} \
        --realm ${REALM} \
        --client ${CLIENT}

        ## remove empty strings and parse command lines
        readarray -t lines <<< "$(echo "${COMMAND}" | sed '/^$/d')"

        ## Execute kcadm.sh for each command line
        for l in "${lines[@]}";
        do
          echo "::debug title=command execution::Executing command $l"
          eval "/tmp/keycloak/bin/kcadm.sh $l";
        done
