name: ci

on:
  push:
    branches:
      - "demo"
  pull_request:
    branches:
      - "demo"

jobs:
  quarkus:
    runs-on: ubuntu-latest
    steps:
      - name: Init Keycloak
        run: |
          docker run -d --name keycloak -p 8080:8080 \
          -e KEYCLOAK_ADMIN=admin \
          -e KEYCLOAK_ADMIN_PASSWORD=admin \
          quay.io/keycloak/keycloak:latest start-dev
      - name: Keycloak Admin CLI
        uses: carlosthe19916/keycloak-action@master
        with:
          version: latest
          server: http://keycloak:8080
          username: admin
          password: admin
          kcadm: |
            update realms/master -s sslRequired=NONE --server http://keycloak:8080
