on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  test:
    uses: ./.github/workflows/keycloak.yaml
    strategy:
      matrix:
        keycloak-version: [latest]
      fail-fast: false
    with:
      keycloak-version: ${{ matrix.keycloak-version }}
