name: Keycloak

on:
  workflow_call:
    inputs:
      keycloak_version:
        description: "Version of Keycloak to test"
        default: "latest"
        required: true
        type: string
  workflow_dispatch:
    inputs:
      keycloak_version:
        description: "Version of Keycloak to test"
        default: "latest"
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start Keycloak
        run: |
          docker run -d --name keycloak -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=password quay.io/keycloak/keycloak:${{ github.event.inputs.keycloak_version }}
      - name: Keycloak Admin CLI
        uses: carlosthe19916/keycloak-action@master
        with:
          version: ${{ github.event.inputs.keycloak_version }}
          server: http://localhost:8080/auth
          username: admin
          password: password
          kcadm: get realms
